// 2026-2027 MEB aktif öğretim programlarına göre hazırlanmış Konu Takibi kataloğu.
// 5-7 ve 9-11: Türkiye Yüzyılı Maarif Modeli; 8 ve 12: 2026-27'de yürürlükte kalan program.
// Etiketler MEB tema/ünite/içerik çerçevelerinin takip için kısa, özgün özetleridir.
export const CURRICULUM_VERSION = "2026-2027";
export type CurriculumTopic = { id: string; label: string };
export type CurriculumSubject = { id: string; label: string; topics: CurriculumTopic[] };
export type CurriculumGrade = { id: string; label: string; group: "Ortaokul" | "Lise"; sourceUrl: string; subjects: CurriculumSubject[] };
const MEB_TYMM = "https://tymm.meb.gov.tr/ogretim-programlari";
const MEB_LEGACY = "https://mufredat.meb.gov.tr/Programlar.aspx";

export const CURRICULUM: CurriculumGrade[] = [
  { id: "5", label: "5. Sınıf", group: "Ortaokul", sourceUrl: MEB_TYMM, subjects: [
    { id: "turkce", label: "Türkçe", topics: [
      { id: "meb26-5-turkce-oyun-dunyasi", label: "Oyun Dünyası" },
      { id: "meb26-5-turkce-ataturk-u-tanimak", label: "Atatürk’ü Tanımak" },
      { id: "meb26-5-turkce-duygularimi-taniyorum", label: "Duygularımı Tanıyorum" },
      { id: "meb26-5-turkce-geleneklerimiz", label: "Geleneklerimiz" },
      { id: "meb26-5-turkce-iletisim-ve-sosyal-iliskiler", label: "İletişim ve Sosyal İlişkiler" },
      { id: "meb26-5-turkce-saglikli-yasiyorum", label: "Sağlıklı Yaşıyorum" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-5-matematik-sayilar-ve-nicelikler-1-cok-basamakli-dogal-sayilar-ve-dort-islem", label: "Sayılar ve Nicelikler (1): çok basamaklı doğal sayılar ve dört işlem" },
      { id: "meb26-5-matematik-sayilar-ve-nicelikler-2-kesir-ondalik-ve-yuzde-gosterimleri", label: "Sayılar ve Nicelikler (2): kesir, ondalık ve yüzde gösterimleri" },
      { id: "meb26-5-matematik-islemlerden-cebirsel-dusunmeye-islem-ozellikleri-oruntu-ve-esitlik", label: "İşlemlerden Cebirsel Düşünmeye: işlem özellikleri, örüntü ve eşitlik" },
      { id: "meb26-5-matematik-geometrik-sekiller-temel-geometrik-sekiller-ve-ozellikleri", label: "Geometrik Şekiller: temel geometrik şekiller ve özellikleri" },
      { id: "meb26-5-matematik-geometrik-nicelikler-uzunluk-cevre-ve-alan", label: "Geometrik Nicelikler: uzunluk, çevre ve alan" },
      { id: "meb26-5-matematik-istatistiksel-arastirma-sureci-veri-toplama-temsil-ve-yorumlama", label: "İstatistiksel Araştırma Süreci: veri toplama, temsil ve yorumlama" },
      { id: "meb26-5-matematik-veriden-olasiliga-deneysel-olasilik-ve-tahmin", label: "Veriden Olasılığa: deneysel olasılık ve tahmin" },
    ] },
    { id: "fen-bilimleri", label: "Fen Bilimleri", topics: [
      { id: "meb26-5-fen-bilimleri-gokyuzundeki-komsularimiz-ve-biz-gunes-ay-evreler-ve-hareketler", label: "Gökyüzündeki Komşularımız ve Biz: Güneş, Ay, evreler ve hareketler" },
      { id: "meb26-5-fen-bilimleri-kuvveti-taniyalim-kuvvet-dinamometre-kutle-agirlik-ve-surtunme", label: "Kuvveti Tanıyalım: kuvvet, dinamometre, kütle-ağırlık ve sürtünme" },
      { id: "meb26-5-fen-bilimleri-canlilarin-yapisina-yolculuk-hucre-doku-organ-sistem-ve-destek-hareket", label: "Canlıların Yapısına Yolculuk: hücre, doku-organ-sistem ve destek-hareket" },
      { id: "meb26-5-fen-bilimleri-isigin-dunyasi-isigin-yayilmasi-yansimasi-ve-maddelerle-etkilesimi", label: "Işığın Dünyası: ışığın yayılması, yansıması ve maddelerle etkileşimi" },
      { id: "meb26-5-fen-bilimleri-maddenin-dogasi-tanecikli-yapi-isi-sicaklik-isi-iletimi-ve-yalitim", label: "Maddenin Doğası: tanecikli yapı, ısı-sıcaklık, ısı iletimi ve yalıtım" },
      { id: "meb26-5-fen-bilimleri-yasamimizdaki-elektrik-devre-elemanlari-ve-elektrik-devreleri", label: "Yaşamımızdaki Elektrik: devre elemanları ve elektrik devreleri" },
      { id: "meb26-5-fen-bilimleri-surdurulebilir-yasam-ve-geri-donusum-cevre-kaynaklar-ve-geri-donusum", label: "Sürdürülebilir Yaşam ve Geri Dönüşüm: çevre, kaynaklar ve geri dönüşüm" },
    ] },
    { id: "sosyal-bilgiler", label: "Sosyal Bilgiler", topics: [
      { id: "meb26-5-sosyal-bilgiler-birlikte-yasamak-gruplar-roller-hak-sorumluluk-kultur-ve-dayanisma", label: "Birlikte Yaşamak: gruplar, roller, hak-sorumluluk, kültür ve dayanışma" },
      { id: "meb26-5-sosyal-bilgiler-evimiz-dunya-konum-harita-dogal-ve-beser-cevre", label: "Evimiz Dünya: konum, harita, doğal ve beşerî çevre" },
      { id: "meb26-5-sosyal-bilgiler-ortak-mirasimiz-anadolu-ve-ortak-kulturel-miras", label: "Ortak Mirasımız: Anadolu ve ortak kültürel miras" },
      { id: "meb26-5-sosyal-bilgiler-yasayan-demokrasimiz-haklar-kurumlar-ve-katilim", label: "Yaşayan Demokrasimiz: haklar, kurumlar ve katılım" },
      { id: "meb26-5-sosyal-bilgiler-hayatimizdaki-ekonomi-kaynaklar-butce-ve-ekonomik-faaliyetler", label: "Hayatımızdaki Ekonomi: kaynaklar, bütçe ve ekonomik faaliyetler" },
      { id: "meb26-5-sosyal-bilgiler-teknoloji-ve-sosyal-bilimler-teknoloji-bilim-ve-toplumsal-etkiler", label: "Teknoloji ve Sosyal Bilimler: teknoloji, bilim ve toplumsal etkiler" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-5-ingilizce-school-life-people-places-rules-clubs-and-countries", label: "School Life: people, places, rules, clubs and countries" },
      { id: "meb26-5-ingilizce-classroom-life-rules-subjects-timetables-objects-days-and-time", label: "Classroom Life: rules, subjects, timetables, objects, days and time" },
      { id: "meb26-5-ingilizce-personal-life-body-physical-features-clothes-and-daily-routines", label: "Personal Life: body, physical features, clothes and daily routines" },
      { id: "meb26-5-ingilizce-family-life-home-family-home-and-everyday-life", label: "Family Life & Home: family, home and everyday life" },
      { id: "meb26-5-ingilizce-life-in-the-neighbourhood-city-places-attractions-and-houses", label: "Life in the Neighbourhood & City: places, attractions and houses" },
      { id: "meb26-5-ingilizce-life-in-the-world-food-restaurants-and-city-food-events", label: "Life in the World: food, restaurants and city food events" },
      { id: "meb26-5-ingilizce-life-in-nature-nature-animals-and-environment", label: "Life in Nature: nature, animals and environment" },
      { id: "meb26-5-ingilizce-life-in-the-universe-future-earth-holidays-and-future-plans", label: "Life in the Universe & Future: Earth, holidays and future plans" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-5-din-kulturu-ve-ahlak-bilgisi-allah-inanci", label: "Allah İnancı" },
      { id: "meb26-5-din-kulturu-ve-ahlak-bilgisi-namaz", label: "Namaz" },
      { id: "meb26-5-din-kulturu-ve-ahlak-bilgisi-kur-an-i-kerim", label: "Kur’an-ı Kerim" },
      { id: "meb26-5-din-kulturu-ve-ahlak-bilgisi-peygamber-kissalari-ve-hz-muhammed", label: "Peygamber Kıssaları ve Hz. Muhammed" },
      { id: "meb26-5-din-kulturu-ve-ahlak-bilgisi-mimarimizde-din-motifler", label: "Mimarimizde Dinî Motifler" },
    ] },
  ] },
  { id: "6", label: "6. Sınıf", group: "Ortaokul", sourceUrl: MEB_TYMM, subjects: [
    { id: "turkce", label: "Türkçe", topics: [
      { id: "meb26-6-turkce-dilimizin-zenginligi", label: "Dilimizin Zenginliği" },
      { id: "meb26-6-turkce-bagimsizlik-yolu", label: "Bağımsızlık Yolu" },
      { id: "meb26-6-turkce-farkli-dunyalar", label: "Farklı Dünyalar" },
      { id: "meb26-6-turkce-iletisim-ve-sosyal-iliskiler", label: "İletişim ve Sosyal İlişkiler" },
      { id: "meb26-6-turkce-bilim-ve-teknoloji", label: "Bilim ve Teknoloji" },
      { id: "meb26-6-turkce-lider-ruhlar", label: "Lider Ruhlar" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-6-matematik-sayilar-ve-nicelikler-1-carpanlar-katlar-bolunebilme-ve-asal-sayilar", label: "Sayılar ve Nicelikler (1): çarpanlar, katlar, bölünebilme ve asal sayılar" },
      { id: "meb26-6-matematik-sayilar-ve-nicelikler-2-kesirler-ondalik-gosterim-yuzde-ve-olcme", label: "Sayılar ve Nicelikler (2): kesirler, ondalık gösterim, yüzde ve ölçme" },
      { id: "meb26-6-matematik-islemlerden-cebirsel-dusunmeye-cebirsel-ifadeler-ve-degisimler", label: "İşlemlerden Cebirsel Düşünmeye: cebirsel ifadeler ve değişimler" },
      { id: "meb26-6-matematik-geometrik-sekiller-aci-cokgen-ve-geometrik-iliskiler", label: "Geometrik Şekiller: açı, çokgen ve geometrik ilişkiler" },
      { id: "meb26-6-matematik-geometrik-nicelikler-alan-cember-ve-olcme", label: "Geometrik Nicelikler: alan, çember ve ölçme" },
      { id: "meb26-6-matematik-istatistiksel-arastirma-sureci-veri-toplama-ve-yorumlama", label: "İstatistiksel Araştırma Süreci: veri toplama ve yorumlama" },
      { id: "meb26-6-matematik-veriden-olasiliga-olasilik-ve-tahmin", label: "Veriden Olasılığa: olasılık ve tahmin" },
    ] },
    { id: "fen-bilimleri", label: "Fen Bilimleri", topics: [
      { id: "meb26-6-fen-bilimleri-gunes-sistemi-ve-tutulmalar-gezegenler-gunes-ve-ay-tutulmalari", label: "Güneş Sistemi ve Tutulmalar: gezegenler, Güneş ve Ay tutulmaları" },
      { id: "meb26-6-fen-bilimleri-kuvvetin-etkisinde-hareket-surat-hiz-kuvvet-ve-hareket", label: "Kuvvetin Etkisinde Hareket: sürat, hız, kuvvet ve hareket" },
      { id: "meb26-6-fen-bilimleri-canlilarda-sistemler-ureme-buyume-sinir-endokrin-sistem-ve-ergenlik", label: "Canlılarda Sistemler: üreme, büyüme, sinir-endokrin sistem ve ergenlik" },
      { id: "meb26-6-fen-bilimleri-isigin-yansimasi-ve-renkler-yansima-aynalar-ve-renk", label: "Işığın Yansıması ve Renkler: yansıma, aynalar ve renk" },
      { id: "meb26-6-fen-bilimleri-maddenin-ayirt-edici-ozellikleri-yogunluk-h-l-degisimi-ve-isi", label: "Maddenin Ayırt Edici Özellikleri: yoğunluk, hâl değişimi ve ısı" },
      { id: "meb26-6-fen-bilimleri-elektrigin-iletimi-ve-direnc-iletken-yalitkan-direnc-ve-ampul-parlakli", label: "Elektriğin İletimi ve Direnç: iletken-yalıtkan, direnç ve ampul parlaklığı" },
      { id: "meb26-6-fen-bilimleri-surdurulebilir-yasam-ve-etkilesim-cevre-ve-surdurulebilirlik", label: "Sürdürülebilir Yaşam ve Etkileşim: çevre ve sürdürülebilirlik" },
    ] },
    { id: "sosyal-bilgiler", label: "Sosyal Bilgiler", topics: [
      { id: "meb26-6-sosyal-bilgiler-birlikte-yasamak-degisen-roller-kulturel-baglar-ve-toplumsal-sorunlar", label: "Birlikte Yaşamak: değişen roller, kültürel bağlar ve toplumsal sorunlar" },
      { id: "meb26-6-sosyal-bilgiler-evimiz-dunya-cografi-konum-dogal-ortam-ve-nufus", label: "Evimiz Dünya: coğrafi konum, doğal ortam ve nüfus" },
      { id: "meb26-6-sosyal-bilgiler-ortak-mirasimiz-turklerin-ve-anadolu-nun-tarih-kulturel-mirasi", label: "Ortak Mirasımız: Türklerin ve Anadolu’nun tarihî-kültürel mirası" },
      { id: "meb26-6-sosyal-bilgiler-yasayan-demokrasimiz-yonetim-haklar-ve-demokratik-katilim", label: "Yaşayan Demokrasimiz: yönetim, haklar ve demokratik katılım" },
      { id: "meb26-6-sosyal-bilgiler-hayatimizdaki-ekonomi-uretim-kaynaklar-ve-ekonomik-kararlar", label: "Hayatımızdaki Ekonomi: üretim, kaynaklar ve ekonomik kararlar" },
      { id: "meb26-6-sosyal-bilgiler-teknoloji-ve-sosyal-bilimler-ulasim-iletisim-telif-ve-patent", label: "Teknoloji ve Sosyal Bilimler: ulaşım-iletişim, telif ve patent" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-6-ingilizce-school-life-people-rules-leadership-and-school-activities", label: "School Life: people, rules, leadership and school activities" },
      { id: "meb26-6-ingilizce-classroom-life-daily-study-routines-classroom-learning-and-numbers", label: "Classroom Life: daily-study routines, classroom learning and numbers" },
      { id: "meb26-6-ingilizce-personal-life-well-being-health-habits-and-well-being", label: "Personal Life & Well-Being: health, habits and well-being" },
      { id: "meb26-6-ingilizce-family-life-home-family-relationships-and-home-life", label: "Family Life & Home: family relationships and home life" },
      { id: "meb26-6-ingilizce-life-in-the-neighbourhood-city-events-festivals-and-transportation", label: "Life in the Neighbourhood & City: events, festivals and transportation" },
      { id: "meb26-6-ingilizce-life-in-the-world-culture-countries-languages-foods-and-events", label: "Life in the World & Culture: countries, languages, foods and events" },
      { id: "meb26-6-ingilizce-life-in-nature-global-problems-nature-activities-environmental-problem", label: "Life in Nature & Global Problems: nature activities, environmental problems and solutions" },
      { id: "meb26-6-ingilizce-life-in-the-universe-future-science-universe-and-future", label: "Life in the Universe & Future: science, universe and future" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-6-din-kulturu-ve-ahlak-bilgisi-peygamber-ve-ilahi-kitap-inanci", label: "Peygamber ve İlahi Kitap İnancı" },
      { id: "meb26-6-din-kulturu-ve-ahlak-bilgisi-namaz-ve-ibadet-bilinci", label: "Namaz ve İbadet Bilinci" },
      { id: "meb26-6-din-kulturu-ve-ahlak-bilgisi-zararli-aliskanliklar", label: "Zararlı Alışkanlıklar" },
      { id: "meb26-6-din-kulturu-ve-ahlak-bilgisi-hz-muhammed-in-hayati", label: "Hz. Muhammed’in Hayatı" },
      { id: "meb26-6-din-kulturu-ve-ahlak-bilgisi-temel-degerlerimiz", label: "Temel Değerlerimiz" },
    ] },
  ] },
  { id: "7", label: "7. Sınıf", group: "Ortaokul", sourceUrl: MEB_TYMM, subjects: [
    { id: "turkce", label: "Türkçe", topics: [
      { id: "meb26-7-turkce-hayat-boyu-gelisim", label: "Hayat Boyu Gelişim" },
      { id: "meb26-7-turkce-bir-hilal-ugruna", label: "Bir Hilal Uğruna" },
      { id: "meb26-7-turkce-iletisim-ve-sosyal-iliskiler", label: "İletişim ve Sosyal İlişkiler" },
      { id: "meb26-7-turkce-turk-sanati", label: "Türk Sanatı" },
      { id: "meb26-7-turkce-okuma-kulturu", label: "Okuma Kültürü" },
      { id: "meb26-7-turkce-hak-ve-sorumluluklar", label: "Hak ve Sorumluluklar" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-7-matematik-sayilar-ve-nicelikler-1-tam-ve-rasyonel-sayilar", label: "Sayılar ve Nicelikler (1): tam ve rasyonel sayılar" },
      { id: "meb26-7-matematik-sayilar-ve-nicelikler-2-oran-oranti-ve-nicelik-iliskileri", label: "Sayılar ve Nicelikler (2): oran, orantı ve nicelik ilişkileri" },
      { id: "meb26-7-matematik-islemlerden-cebirsel-dusunmeye-cebirsel-ifadeler-esitlik-ve-degisim", label: "İşlemlerden Cebirsel Düşünmeye: cebirsel ifadeler, eşitlik ve değişim" },
      { id: "meb26-7-matematik-geometrik-sekiller-dogrular-acilar-ve-cokgenler", label: "Geometrik Şekiller: doğrular, açılar ve çokgenler" },
      { id: "meb26-7-matematik-geometrik-nicelikler-1-alan-ve-hacim", label: "Geometrik Nicelikler (1): alan ve hacim" },
      { id: "meb26-7-matematik-geometrik-nicelikler-2-cember-daire-ve-olcme", label: "Geometrik Nicelikler (2): çember, daire ve ölçme" },
      { id: "meb26-7-matematik-istatistiksel-arastirma-sureci-veri-analizi-ve-cikarim", label: "İstatistiksel Araştırma Süreci: veri analizi ve çıkarım" },
      { id: "meb26-7-matematik-veriden-olasiliga-olasilik-ve-veri-temelli-tahmin", label: "Veriden Olasılığa: olasılık ve veri temelli tahmin" },
    ] },
    { id: "fen-bilimleri", label: "Fen Bilimleri", topics: [
      { id: "meb26-7-fen-bilimleri-uzay-cagi-uzay-teknolojileri-yildizlar-galaksiler-ve-evren", label: "Uzay Çağı: uzay teknolojileri, yıldızlar, galaksiler ve evren" },
      { id: "meb26-7-fen-bilimleri-kuvvet-ve-enerjiyi-kesfedelim-kuvvet-is-enerji-ve-donusumler", label: "Kuvvet ve Enerjiyi Keşfedelim: kuvvet, iş, enerji ve dönüşümler" },
      { id: "meb26-7-fen-bilimleri-vucudumuzdaki-sistemler-sindirim-dolasim-solunum-ve-bosaltim", label: "Vücudumuzdaki Sistemler: sindirim, dolaşım, solunum ve boşaltım" },
      { id: "meb26-7-fen-bilimleri-isigin-kirilmasi-ve-mercekler-kirilma-mercekler-ve-optik-araclar", label: "Işığın Kırılması ve Mercekler: kırılma, mercekler ve optik araçlar" },
      { id: "meb26-7-fen-bilimleri-maddenin-dogasina-yolculuk-atom-element-bilesik-karisim-ve-ayirma", label: "Maddenin Doğasına Yolculuk: atom, element, bileşik, karışım ve ayırma" },
      { id: "meb26-7-fen-bilimleri-elektriklenme-elektrik-yukleri-ve-elektriklenme", label: "Elektriklenme: elektrik yükleri ve elektriklenme" },
      { id: "meb26-7-fen-bilimleri-surdurulebilir-yasam-ve-enerji-besin-zinciri-enerji-su-ve-kaynak-tasar", label: "Sürdürülebilir Yaşam ve Enerji: besin zinciri, enerji, su ve kaynak tasarrufu" },
    ] },
    { id: "sosyal-bilgiler", label: "Sosyal Bilgiler", topics: [
      { id: "meb26-7-sosyal-bilgiler-birlikte-yasamak-etkili-iletisim-firsat-esitligi-ve-mill-meseleler", label: "Birlikte Yaşamak: etkili iletişim, fırsat eşitliği ve millî meseleler" },
      { id: "meb26-7-sosyal-bilgiler-evimiz-dunya-nufus-yerlesme-ve-cografi-iliskiler", label: "Evimiz Dünya: nüfus, yerleşme ve coğrafi ilişkiler" },
      { id: "meb26-7-sosyal-bilgiler-ortak-mirasimiz-turk-islam-ve-dunya-mirasi", label: "Ortak Mirasımız: Türk-İslam ve dünya mirası" },
      { id: "meb26-7-sosyal-bilgiler-yasayan-demokrasimiz-demokrasi-haklar-ve-katilim", label: "Yaşayan Demokrasimiz: demokrasi, haklar ve katılım" },
      { id: "meb26-7-sosyal-bilgiler-hayatimizdaki-ekonomi-uretim-meslekler-ve-ekonomik-yasam", label: "Hayatımızdaki Ekonomi: üretim, meslekler ve ekonomik yaşam" },
      { id: "meb26-7-sosyal-bilgiler-teknoloji-ve-sosyal-bilimler-bilimsel-gelismeler-ve-toplumsal-degisim", label: "Teknoloji ve Sosyal Bilimler: bilimsel gelişmeler ve toplumsal değişim" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-7-ingilizce-school-life-education-school-activities-competitions-and-celebrations", label: "School Life & Education: school activities, competitions and celebrations" },
      { id: "meb26-7-ingilizce-classroom-life-learning-learning-technologies-activities-and-numbers", label: "Classroom Life & Learning: learning technologies, activities and numbers" },
      { id: "meb26-7-ingilizce-personal-life-well-being-body-illnesses-health-and-technology", label: "Personal Life & Well-Being: body, illnesses, health and technology" },
      { id: "meb26-7-ingilizce-family-life-home-hobbies-family-and-generation-gap", label: "Family Life & Home: hobbies, family and generation gap" },
      { id: "meb26-7-ingilizce-life-in-the-neighbourhood-city-social-life-community-and-social-life", label: "Life in the Neighbourhood, City & Social Life: community and social life" },
      { id: "meb26-7-ingilizce-life-in-the-world-culture-capitals-landmarks-and-international-sports", label: "Life in the World & Culture: capitals, landmarks and international sports" },
      { id: "meb26-7-ingilizce-life-in-nature-animals-natural-resources-and-protecting-nature", label: "Life in Nature: animals, natural resources and protecting nature" },
      { id: "meb26-7-ingilizce-life-in-the-universe-future-space-technology-and-robots", label: "Life in the Universe & Future: space technology and robots" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-7-din-kulturu-ve-ahlak-bilgisi-melek-ve-ahiret-inanci-varliklar-ahiret-asamalari-ve-n-s-suresi", label: "Melek ve Ahiret İnancı: varlıklar, ahiret aşamaları ve Nâs suresi" },
      { id: "meb26-7-din-kulturu-ve-ahlak-bilgisi-hac-umre-ve-kurban-ibadetler-mek-nlar-yardimlasma-ve-k-fir-n-suresi", label: "Hac, Umre ve Kurban: ibadetler, mekânlar, yardımlaşma ve Kâfirûn suresi" },
      { id: "meb26-7-din-kulturu-ve-ahlak-bilgisi-islam-dusuncesinde-yorumlar-din-anlayisi-itikad-fikh-tasavvuf-yorumlar", label: "İslam Düşüncesinde Yorumlar: din anlayışı, itikadî-fıkhî-tasavvufî yorumlar" },
      { id: "meb26-7-din-kulturu-ve-ahlak-bilgisi-peygamber-olarak-hz-muhammed-mekke-hicret-medine-ve-nasr-suresi", label: "Peygamber Olarak Hz. Muhammed: Mekke, Hicret, Medine ve Nasr suresi" },
      { id: "meb26-7-din-kulturu-ve-ahlak-bilgisi-yasayan-dunya-dinleri-yahudilik-hristiyanlik-hinduizm-ve-budizm", label: "Yaşayan Dünya Dinleri: Yahudilik, Hristiyanlık, Hinduizm ve Budizm" },
    ] },
  ] },
  { id: "8", label: "8. Sınıf (LGS)", group: "Ortaokul", sourceUrl: MEB_LEGACY, subjects: [
    { id: "turkce", label: "Türkçe", topics: [
      { id: "meb26-8-turkce-sozcukte-anlam", label: "Sözcükte Anlam" },
      { id: "meb26-8-turkce-cumlede-anlam", label: "Cümlede Anlam" },
      { id: "meb26-8-turkce-paragrafta-anlam-ve-metin-yorumlama", label: "Paragrafta Anlam ve Metin Yorumlama" },
      { id: "meb26-8-turkce-fiilimsiler", label: "Fiilimsiler" },
      { id: "meb26-8-turkce-cumlenin-ogeleri", label: "Cümlenin Ögeleri" },
      { id: "meb26-8-turkce-fiilde-cati", label: "Fiilde Çatı" },
      { id: "meb26-8-turkce-cumle-turleri", label: "Cümle Türleri" },
      { id: "meb26-8-turkce-anlatim-bozukluklari", label: "Anlatım Bozuklukları" },
      { id: "meb26-8-turkce-yazim-kurallari", label: "Yazım Kuralları" },
      { id: "meb26-8-turkce-noktalama-isaretleri", label: "Noktalama İşaretleri" },
      { id: "meb26-8-turkce-soz-sanatlari", label: "Söz Sanatları" },
      { id: "meb26-8-turkce-gorsel-grafik-ve-tablo-yorumlama", label: "Görsel, Grafik ve Tablo Yorumlama" },
      { id: "meb26-8-turkce-sozel-mantik-ve-muhakeme", label: "Sözel Mantık ve Muhakeme" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-8-matematik-carpanlar-ve-katlar", label: "Çarpanlar ve Katlar" },
      { id: "meb26-8-matematik-uslu-ifadeler", label: "Üslü İfadeler" },
      { id: "meb26-8-matematik-karekoklu-ifadeler", label: "Kareköklü İfadeler" },
      { id: "meb26-8-matematik-veri-analizi", label: "Veri Analizi" },
      { id: "meb26-8-matematik-basit-olaylarin-olma-olasiligi", label: "Basit Olayların Olma Olasılığı" },
      { id: "meb26-8-matematik-cebirsel-ifadeler-ve-ozdeslikler", label: "Cebirsel İfadeler ve Özdeşlikler" },
      { id: "meb26-8-matematik-dogrusal-denklemler", label: "Doğrusal Denklemler" },
      { id: "meb26-8-matematik-esitsizlikler", label: "Eşitsizlikler" },
      { id: "meb26-8-matematik-ucgenler", label: "Üçgenler" },
      { id: "meb26-8-matematik-eslik-ve-benzerlik", label: "Eşlik ve Benzerlik" },
      { id: "meb26-8-matematik-donusum-geometrisi", label: "Dönüşüm Geometrisi" },
      { id: "meb26-8-matematik-geometrik-cisimler", label: "Geometrik Cisimler" },
    ] },
    { id: "fen-bilimleri", label: "Fen Bilimleri", topics: [
      { id: "meb26-8-fen-bilimleri-mevsimler-ve-iklim", label: "Mevsimler ve İklim" },
      { id: "meb26-8-fen-bilimleri-dna-ve-genetik-kod", label: "DNA ve Genetik Kod" },
      { id: "meb26-8-fen-bilimleri-basinc", label: "Basınç" },
      { id: "meb26-8-fen-bilimleri-madde-ve-endustri", label: "Madde ve Endüstri" },
      { id: "meb26-8-fen-bilimleri-basit-makineler", label: "Basit Makineler" },
      { id: "meb26-8-fen-bilimleri-enerji-donusumleri-ve-cevre-bilimi", label: "Enerji Dönüşümleri ve Çevre Bilimi" },
      { id: "meb26-8-fen-bilimleri-elektrik-yukleri-ve-elektrik-enerjisi", label: "Elektrik Yükleri ve Elektrik Enerjisi" },
    ] },
    { id: "t-c-inkilap-tarihi-ve-ataturkculuk", label: "T.C. İnkılap Tarihi ve Atatürkçülük", topics: [
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-bir-kahraman-doguyor", label: "Bir Kahraman Doğuyor" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-mill-uyanis-bagimsizlik-yolunda-atilan-adimlar", label: "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-mill-bir-destan-ya-istiklal-ya-olum", label: "Millî Bir Destan: Ya İstiklal Ya Ölüm!" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-ataturkculuk-ve-cagdaslasan-turkiye", label: "Atatürkçülük ve Çağdaşlaşan Türkiye" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-demokratiklesme-cabalari", label: "Demokratikleşme Çabaları" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-ataturk-donemi-turk-dis-politikasi", label: "Atatürk Dönemi Türk Dış Politikası" },
      { id: "meb26-8-t-c-inkilap-tarihi-ve-ataturkculuk-ataturk-un-olumu-ve-sonrasi", label: "Atatürk’ün Ölümü ve Sonrası" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-8-ingilizce-friendship", label: "Friendship" },
      { id: "meb26-8-ingilizce-teen-life", label: "Teen Life" },
      { id: "meb26-8-ingilizce-in-the-kitchen", label: "In The Kitchen" },
      { id: "meb26-8-ingilizce-on-the-phone", label: "On The Phone" },
      { id: "meb26-8-ingilizce-the-internet", label: "The Internet" },
      { id: "meb26-8-ingilizce-adventures", label: "Adventures" },
      { id: "meb26-8-ingilizce-tourism", label: "Tourism" },
      { id: "meb26-8-ingilizce-chores", label: "Chores" },
      { id: "meb26-8-ingilizce-science", label: "Science" },
      { id: "meb26-8-ingilizce-natural-forces", label: "Natural Forces" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-8-din-kulturu-ve-ahlak-bilgisi-kader-inanci", label: "Kader İnancı" },
      { id: "meb26-8-din-kulturu-ve-ahlak-bilgisi-zek-t-ve-sadaka", label: "Zekât ve Sadaka" },
      { id: "meb26-8-din-kulturu-ve-ahlak-bilgisi-din-ve-hayat", label: "Din ve Hayat" },
      { id: "meb26-8-din-kulturu-ve-ahlak-bilgisi-hz-muhammed-in-ornekligi", label: "Hz. Muhammed’in Örnekliği" },
      { id: "meb26-8-din-kulturu-ve-ahlak-bilgisi-kur-an-i-kerim-ve-ozellikleri", label: "Kur’an-ı Kerim ve Özellikleri" },
    ] },
  ] },
  { id: "9", label: "9. Sınıf", group: "Lise", sourceUrl: MEB_TYMM, subjects: [
    { id: "turk-dili-ve-edebiyati", label: "Türk Dili ve Edebiyatı", topics: [
      { id: "meb26-9-turk-dili-ve-edebiyati-sozun-inceligi", label: "Sözün İnceliği" },
      { id: "meb26-9-turk-dili-ve-edebiyati-anlam-arayisi", label: "Anlam Arayışı" },
      { id: "meb26-9-turk-dili-ve-edebiyati-anlamin-yapi-taslari", label: "Anlamın Yapı Taşları" },
      { id: "meb26-9-turk-dili-ve-edebiyati-dilin-zenginligi", label: "Dilin Zenginliği" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-9-matematik-sayilar", label: "Sayılar" },
      { id: "meb26-9-matematik-nicelikler-ve-degisimler", label: "Nicelikler ve Değişimler" },
      { id: "meb26-9-matematik-geometrik-sekiller", label: "Geometrik Şekiller" },
      { id: "meb26-9-matematik-eslik-ve-benzerlik", label: "Eşlik ve Benzerlik" },
      { id: "meb26-9-matematik-algoritma-ve-bilisim", label: "Algoritma ve Bilişim" },
      { id: "meb26-9-matematik-istatistiksel-arastirma-sureci", label: "İstatistiksel Araştırma Süreci" },
      { id: "meb26-9-matematik-veriden-olasiliga", label: "Veriden Olasılığa" },
    ] },
    { id: "fizik", label: "Fizik", topics: [
      { id: "meb26-9-fizik-fizik-bilimi-ve-kariyer-kesfi", label: "Fizik Bilimi ve Kariyer Keşfi" },
      { id: "meb26-9-fizik-kuvvet-ve-hareket", label: "Kuvvet ve Hareket" },
      { id: "meb26-9-fizik-akiskanlar", label: "Akışkanlar" },
      { id: "meb26-9-fizik-enerji", label: "Enerji" },
    ] },
    { id: "kimya", label: "Kimya", topics: [
      { id: "meb26-9-kimya-etkilesim-kimya-hayattir-ve-atomdan-periyodik-tabloya", label: "Etkileşim: Kimya Hayattır ve Atomdan Periyodik Tabloya" },
      { id: "meb26-9-kimya-cesitlilik-kimyasal-baglar-ve-maddelerin-cesitliligi", label: "Çeşitlilik: kimyasal bağlar ve maddelerin çeşitliliği" },
      { id: "meb26-9-kimya-surdurulebilirlik-kimyanin-cevre-ve-surdurulebilirlikle-iliskisi", label: "Sürdürülebilirlik: kimyanın çevre ve sürdürülebilirlikle ilişkisi" },
    ] },
    { id: "biyoloji", label: "Biyoloji", topics: [
      { id: "meb26-9-biyoloji-yasam-biyolojinin-temelleri-ve-canlilarin-ortak-ozellikleri", label: "Yaşam: biyolojinin temelleri ve canlıların ortak özellikleri" },
      { id: "meb26-9-biyoloji-organizasyon-hucreden-organizmaya-yapi-ve-duzen", label: "Organizasyon: hücreden organizmaya yapı ve düzen" },
    ] },
    { id: "tarih", label: "Tarih", topics: [
      { id: "meb26-9-tarih-gecmisin-insa-surecinde-tarih", label: "Geçmişin İnşa Sürecinde Tarih" },
      { id: "meb26-9-tarih-eski-cag-medeniyetleri", label: "Eski Çağ Medeniyetleri" },
      { id: "meb26-9-tarih-orta-cag-medeniyetleri", label: "Orta Çağ Medeniyetleri" },
      { id: "meb26-9-tarih-turklerin-islamiyet-i-kabulu-ve-ilk-turk-islam-devletleri", label: "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri" },
    ] },
    { id: "cografya", label: "Coğrafya", topics: [
      { id: "meb26-9-cografya-cografyanin-dogasi", label: "Coğrafyanın Doğası" },
      { id: "meb26-9-cografya-mek-nsal-bilgi-teknolojileri", label: "Mekânsal Bilgi Teknolojileri" },
      { id: "meb26-9-cografya-dogal-sistemler-ve-surecler", label: "Doğal Sistemler ve Süreçler" },
      { id: "meb26-9-cografya-beser-sistemler-ve-surecler", label: "Beşerî Sistemler ve Süreçler" },
      { id: "meb26-9-cografya-ekonomik-faaliyetler-ve-etkileri", label: "Ekonomik Faaliyetler ve Etkileri" },
      { id: "meb26-9-cografya-afetler-ve-surdurulebilir-cevre", label: "Afetler ve Sürdürülebilir Çevre" },
      { id: "meb26-9-cografya-bolgeler-ulkeler-ve-kuresel-baglantilar", label: "Bölgeler, Ülkeler ve Küresel Bağlantılar" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-9-ingilizce-school-life-education", label: "School Life & Education" },
      { id: "meb26-9-ingilizce-classroom-life-learning", label: "Classroom Life & Learning" },
      { id: "meb26-9-ingilizce-personal-life-well-being", label: "Personal Life & Well-Being" },
      { id: "meb26-9-ingilizce-family-life-home", label: "Family Life & Home" },
      { id: "meb26-9-ingilizce-life-in-the-neighbourhood-city-social-life", label: "Life in the Neighbourhood, City & Social Life" },
      { id: "meb26-9-ingilizce-life-in-the-world-culture", label: "Life in the World & Culture" },
      { id: "meb26-9-ingilizce-life-in-nature", label: "Life in Nature" },
      { id: "meb26-9-ingilizce-life-in-the-universe-future", label: "Life in the Universe & Future" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-9-din-kulturu-ve-ahlak-bilgisi-bilgi-ve-inanc", label: "Bilgi ve İnanç" },
      { id: "meb26-9-din-kulturu-ve-ahlak-bilgisi-din-ve-ibadet", label: "Din ve İbadet" },
      { id: "meb26-9-din-kulturu-ve-ahlak-bilgisi-ahlak-ve-degerler", label: "Ahlak ve Değerler" },
      { id: "meb26-9-din-kulturu-ve-ahlak-bilgisi-hz-muhammed-ve-genclik", label: "Hz. Muhammed ve Gençlik" },
      { id: "meb26-9-din-kulturu-ve-ahlak-bilgisi-gonul-cografyamiz", label: "Gönül Coğrafyamız" },
    ] },
  ] },
  { id: "10", label: "10. Sınıf", group: "Lise", sourceUrl: MEB_TYMM, subjects: [
    { id: "turk-dili-ve-edebiyati", label: "Türk Dili ve Edebiyatı", topics: [
      { id: "meb26-10-turk-dili-ve-edebiyati-sozun-ezgisi", label: "Sözün Ezgisi" },
      { id: "meb26-10-turk-dili-ve-edebiyati-kelimelerin-ritmi", label: "Kelimelerin Ritmi" },
      { id: "meb26-10-turk-dili-ve-edebiyati-dunden-bugune", label: "Dünden Bugüne" },
      { id: "meb26-10-turk-dili-ve-edebiyati-nesillerin-mirasi", label: "Nesillerin Mirası" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-10-matematik-geometrik-sekiller", label: "Geometrik Şekiller" },
      { id: "meb26-10-matematik-istatistiksel-arastirma-sureci", label: "İstatistiksel Araştırma Süreci" },
      { id: "meb26-10-matematik-sayilar", label: "Sayılar" },
      { id: "meb26-10-matematik-nicelikler-ve-degisimler", label: "Nicelikler ve Değişimler" },
      { id: "meb26-10-matematik-sayma-algoritma-ve-bilisim-sayma-stratejileri-ve-algoritmik-yapi", label: "Sayma, Algoritma ve Bilişim: sayma stratejileri ve algoritmik yapı" },
      { id: "meb26-10-matematik-analitik-inceleme", label: "Analitik İnceleme" },
      { id: "meb26-10-matematik-veriden-olasiliga", label: "Veriden Olasılığa" },
    ] },
    { id: "fizik", label: "Fizik", topics: [
      { id: "meb26-10-fizik-kuvvet-ve-hareket", label: "Kuvvet ve Hareket" },
      { id: "meb26-10-fizik-enerji", label: "Enerji" },
      { id: "meb26-10-fizik-elektrik", label: "Elektrik" },
      { id: "meb26-10-fizik-dalgalar", label: "Dalgalar" },
    ] },
    { id: "kimya", label: "Kimya", topics: [
      { id: "meb26-10-kimya-etkilesim", label: "Etkileşim" },
      { id: "meb26-10-kimya-cesitlilik", label: "Çeşitlilik" },
      { id: "meb26-10-kimya-surdurulebilirlik", label: "Sürdürülebilirlik" },
    ] },
    { id: "biyoloji", label: "Biyoloji", topics: [
      { id: "meb26-10-biyoloji-enerji-canlilarda-enerji-donusumleri", label: "Enerji: canlılarda enerji dönüşümleri" },
      { id: "meb26-10-biyoloji-ekoloji-ekosistem-madde-donguleri-ve-cevre", label: "Ekoloji: ekosistem, madde döngüleri ve çevre" },
    ] },
    { id: "tarih", label: "Tarih", topics: [
      { id: "meb26-10-tarih-turkistan-dan-turkiye-ye", label: "Türkistan’dan Türkiye’ye" },
      { id: "meb26-10-tarih-beylikten-devlete-osmanli", label: "Beylikten Devlete Osmanlı" },
      { id: "meb26-10-tarih-cihan-devleti-osmanli", label: "Cihan Devleti Osmanlı" },
      { id: "meb26-10-tarih-degisen-dunya-dengeleri-ve-osmanli", label: "Değişen Dünya Dengeleri ve Osmanlı" },
    ] },
    { id: "cografya", label: "Coğrafya", topics: [
      { id: "meb26-10-cografya-cografyanin-dogasi", label: "Coğrafyanın Doğası" },
      { id: "meb26-10-cografya-mek-nsal-bilgi-teknolojileri", label: "Mekânsal Bilgi Teknolojileri" },
      { id: "meb26-10-cografya-dogal-sistemler-ve-surecler", label: "Doğal Sistemler ve Süreçler" },
      { id: "meb26-10-cografya-beser-sistemler-ve-surecler", label: "Beşerî Sistemler ve Süreçler" },
      { id: "meb26-10-cografya-ekonomik-faaliyetler-ve-etkileri", label: "Ekonomik Faaliyetler ve Etkileri" },
      { id: "meb26-10-cografya-afetler-ve-surdurulebilir-cevre", label: "Afetler ve Sürdürülebilir Çevre" },
      { id: "meb26-10-cografya-bolgeler-ulkeler-ve-kuresel-baglantilar", label: "Bölgeler, Ülkeler ve Küresel Bağlantılar" },
    ] },
    { id: "felsefe", label: "Felsefe", topics: [
      { id: "meb26-10-felsefe-felsefeyi-tanima", label: "Felsefeyi Tanıma" },
      { id: "meb26-10-felsefe-felsefe-ile-dusunme", label: "Felsefe ile Düşünme" },
      { id: "meb26-10-felsefe-varlik-felsefesi", label: "Varlık Felsefesi" },
      { id: "meb26-10-felsefe-bilgi-felsefesi", label: "Bilgi Felsefesi" },
      { id: "meb26-10-felsefe-ahlak-felsefesi", label: "Ahlak Felsefesi" },
      { id: "meb26-10-felsefe-sanat-felsefesi", label: "Sanat Felsefesi" },
      { id: "meb26-10-felsefe-din-felsefesi", label: "Din Felsefesi" },
      { id: "meb26-10-felsefe-siyaset-felsefesi", label: "Siyaset Felsefesi" },
      { id: "meb26-10-felsefe-bilim-felsefesi", label: "Bilim Felsefesi" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-10-ingilizce-school-life-education", label: "School Life & Education" },
      { id: "meb26-10-ingilizce-classroom-life-learning", label: "Classroom Life & Learning" },
      { id: "meb26-10-ingilizce-personal-life-well-being", label: "Personal Life & Well-Being" },
      { id: "meb26-10-ingilizce-family-life-home", label: "Family Life & Home" },
      { id: "meb26-10-ingilizce-life-in-the-neighbourhood-city-social-life", label: "Life in the Neighbourhood, City & Social Life" },
      { id: "meb26-10-ingilizce-life-in-the-world-culture", label: "Life in the World & Culture" },
      { id: "meb26-10-ingilizce-life-in-nature", label: "Life in Nature" },
      { id: "meb26-10-ingilizce-life-in-the-universe-future", label: "Life in the Universe & Future" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-10-din-kulturu-ve-ahlak-bilgisi-allah-insan-iliskisi", label: "Allah İnsan İlişkisi" },
      { id: "meb26-10-din-kulturu-ve-ahlak-bilgisi-hz-muhammed-ve-genclik", label: "Hz. Muhammed ve Gençlik" },
      { id: "meb26-10-din-kulturu-ve-ahlak-bilgisi-din-ve-hayat", label: "Din ve Hayat" },
      { id: "meb26-10-din-kulturu-ve-ahlak-bilgisi-ahlaki-tutum-ve-davranislar", label: "Ahlaki Tutum ve Davranışlar" },
      { id: "meb26-10-din-kulturu-ve-ahlak-bilgisi-islam-dusuncesinde-yorumlar", label: "İslam Düşüncesinde Yorumlar" },
    ] },
  ] },
  { id: "11", label: "11. Sınıf", group: "Lise", sourceUrl: MEB_TYMM, subjects: [
    { id: "turk-dili-ve-edebiyati", label: "Türk Dili ve Edebiyatı", topics: [
      { id: "meb26-11-turk-dili-ve-edebiyati-bir-diyecegim-var", label: "Bir Diyeceğim Var!" },
      { id: "meb26-11-turk-dili-ve-edebiyati-kultur-yolculugu", label: "Kültür Yolculuğu" },
      { id: "meb26-11-turk-dili-ve-edebiyati-yasamin-izinde", label: "Yaşamın İzinde" },
      { id: "meb26-11-turk-dili-ve-edebiyati-hayatin-aynasi", label: "Hayatın Aynası" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-11-matematik-istatistiksel-arastirma-sureci", label: "İstatistiksel Araştırma Süreci" },
      { id: "meb26-11-matematik-geometrik-sekiller", label: "Geometrik Şekiller" },
      { id: "meb26-11-matematik-nicelikler-ve-degisimler-1", label: "Nicelikler ve Değişimler (1)" },
      { id: "meb26-11-matematik-nicelikler-ve-degisimler-2", label: "Nicelikler ve Değişimler (2)" },
      { id: "meb26-11-matematik-nicelikler-ve-degisimler-3", label: "Nicelikler ve Değişimler (3)" },
    ] },
    { id: "fizik", label: "Fizik", topics: [
      { id: "meb26-11-fizik-kuvvet-ve-hareket-serbest-dusme-iki-boyutta-hareket-newton-yasalari-su", label: "Kuvvet ve Hareket: serbest düşme, iki boyutta hareket, Newton yasaları, sürtünme, limit hız ve çembersel hareket" },
      { id: "meb26-11-fizik-elektrik-ve-manyetizma-elektriksel-alan-manyetik-alan-induksiyon-ve-tr", label: "Elektrik ve Manyetizma: elektriksel alan, manyetik alan, indüksiyon ve transformatörler" },
      { id: "meb26-11-fizik-optik-aydinlanma-aynalar-mercekler-kirilma-fiber-optik-ve-prizmalar", label: "Optik: aydınlanma, aynalar, mercekler, kırılma, fiber optik ve prizmalar" },
    ] },
    { id: "kimya", label: "Kimya", topics: [
      { id: "meb26-11-kimya-etkilesim-enerji-ve-kimyasal-etkilesimler", label: "Etkileşim: enerji ve kimyasal etkileşimler" },
      { id: "meb26-11-kimya-cesitlilik-kimyasal-tepkimelerde-hiz-ve-denge", label: "Çeşitlilik: kimyasal tepkimelerde hız ve denge" },
      { id: "meb26-11-kimya-surdurulebilirlik-kimya-kaynaklar-ve-cevre", label: "Sürdürülebilirlik: kimya, kaynaklar ve çevre" },
    ] },
    { id: "biyoloji", label: "Biyoloji", topics: [
      { id: "meb26-11-biyoloji-tepki-sinir-endokrin-sistem-duyu-ve-organizmanin-cevreye-tepkisi", label: "Tepki: sinir-endokrin sistem, duyu ve organizmanın çevreye tepkisi" },
      { id: "meb26-11-biyoloji-homeostazi-destek-hareket-sindirim-dolasim-solunum-ve-bosaltim-dengesi", label: "Homeostazi: destek-hareket, sindirim, dolaşım, solunum ve boşaltım dengesi" },
    ] },
    { id: "tarih", label: "Tarih", topics: [
      { id: "meb26-11-tarih-degisen-dunyada-osmanli", label: "Değişen Dünyada Osmanlı" },
      { id: "meb26-11-tarih-degisim-caginda-avrupa-ve-osmanli", label: "Değişim Çağında Avrupa ve Osmanlı" },
      { id: "meb26-11-tarih-uluslararasi-iliskilerde-denge-stratejisi", label: "Uluslararası İlişkilerde Denge Stratejisi" },
      { id: "meb26-11-tarih-devrimler-caginda-degisen-devlet-toplum-iliskileri", label: "Devrimler Çağında Değişen Devlet-Toplum İlişkileri" },
    ] },
    { id: "cografya", label: "Coğrafya", topics: [
      { id: "meb26-11-cografya-cografyanin-dogasi", label: "Coğrafyanın Doğası" },
      { id: "meb26-11-cografya-mek-nsal-bilgi-teknolojileri", label: "Mekânsal Bilgi Teknolojileri" },
      { id: "meb26-11-cografya-dogal-sistemler-ve-surecler", label: "Doğal Sistemler ve Süreçler" },
      { id: "meb26-11-cografya-beser-sistemler-ve-surecler", label: "Beşerî Sistemler ve Süreçler" },
      { id: "meb26-11-cografya-ekonomik-faaliyetler-ve-etkileri", label: "Ekonomik Faaliyetler ve Etkileri" },
      { id: "meb26-11-cografya-afetler-ve-surdurulebilir-cevre", label: "Afetler ve Sürdürülebilir Çevre" },
      { id: "meb26-11-cografya-bolgeler-ulkeler-ve-kuresel-baglantilar", label: "Bölgeler, Ülkeler ve Küresel Bağlantılar" },
    ] },
    { id: "felsefe", label: "Felsefe", topics: [
      { id: "meb26-11-felsefe-felsefenin-temel-problemleri", label: "Felsefenin Temel Problemleri" },
      { id: "meb26-11-felsefe-bilgi-felsefesi", label: "Bilgi Felsefesi" },
      { id: "meb26-11-felsefe-varlik-felsefesi", label: "Varlık Felsefesi" },
      { id: "meb26-11-felsefe-ahlak-felsefesi", label: "Ahlak Felsefesi" },
      { id: "meb26-11-felsefe-sanat-felsefesi", label: "Sanat Felsefesi" },
      { id: "meb26-11-felsefe-din-felsefesi", label: "Din Felsefesi" },
      { id: "meb26-11-felsefe-siyaset-felsefesi", label: "Siyaset Felsefesi" },
      { id: "meb26-11-felsefe-bilim-felsefesi", label: "Bilim Felsefesi" },
    ] },
    { id: "ingilizce", label: "İngilizce", topics: [
      { id: "meb26-11-ingilizce-school-life-education", label: "School Life & Education" },
      { id: "meb26-11-ingilizce-classroom-life-learning", label: "Classroom Life & Learning" },
      { id: "meb26-11-ingilizce-personal-life-well-being", label: "Personal Life & Well-Being" },
      { id: "meb26-11-ingilizce-family-life-home", label: "Family Life & Home" },
      { id: "meb26-11-ingilizce-life-in-the-neighbourhood-city-social-life", label: "Life in the Neighbourhood, City & Social Life" },
      { id: "meb26-11-ingilizce-life-in-the-world-culture", label: "Life in the World & Culture" },
      { id: "meb26-11-ingilizce-life-in-nature", label: "Life in Nature" },
      { id: "meb26-11-ingilizce-life-in-the-universe-future", label: "Life in the Universe & Future" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-11-din-kulturu-ve-ahlak-bilgisi-dunya-ve-ahiret", label: "Dünya ve Ahiret" },
      { id: "meb26-11-din-kulturu-ve-ahlak-bilgisi-kur-an-a-gore-hz-muhammed", label: "Kur’an’a Göre Hz. Muhammed" },
      { id: "meb26-11-din-kulturu-ve-ahlak-bilgisi-kur-an-da-bazi-kavramlar", label: "Kur’an’da Bazı Kavramlar" },
      { id: "meb26-11-din-kulturu-ve-ahlak-bilgisi-inancla-ilgili-meseleler", label: "İnançla İlgili Meseleler" },
      { id: "meb26-11-din-kulturu-ve-ahlak-bilgisi-yahudilik-ve-hristiyanlik", label: "Yahudilik ve Hristiyanlık" },
    ] },
  ] },
  { id: "12", label: "12. Sınıf / YKS", group: "Lise", sourceUrl: MEB_LEGACY, subjects: [
    { id: "turk-dili-ve-edebiyati", label: "Türk Dili ve Edebiyatı", topics: [
      { id: "meb26-12-turk-dili-ve-edebiyati-giris-ve-dil-bilgisi-tekrari", label: "Giriş ve Dil Bilgisi Tekrarı" },
      { id: "meb26-12-turk-dili-ve-edebiyati-hik-ye", label: "Hikâye" },
      { id: "meb26-12-turk-dili-ve-edebiyati-siir", label: "Şiir" },
      { id: "meb26-12-turk-dili-ve-edebiyati-roman", label: "Roman" },
      { id: "meb26-12-turk-dili-ve-edebiyati-tiyatro", label: "Tiyatro" },
      { id: "meb26-12-turk-dili-ve-edebiyati-deneme", label: "Deneme" },
      { id: "meb26-12-turk-dili-ve-edebiyati-soylev", label: "Söylev" },
      { id: "meb26-12-turk-dili-ve-edebiyati-cumhuriyet-donemi-turk-edebiyati", label: "Cumhuriyet Dönemi Türk Edebiyatı" },
      { id: "meb26-12-turk-dili-ve-edebiyati-dunya-edebiyatindan-metinler", label: "Dünya Edebiyatından Metinler" },
    ] },
    { id: "matematik", label: "Matematik", topics: [
      { id: "meb26-12-matematik-ustel-ve-logaritmik-fonksiyonlar", label: "Üstel ve Logaritmik Fonksiyonlar" },
      { id: "meb26-12-matematik-diziler", label: "Diziler" },
      { id: "meb26-12-matematik-trigonometri", label: "Trigonometri" },
      { id: "meb26-12-matematik-donusumler", label: "Dönüşümler" },
      { id: "meb26-12-matematik-turev", label: "Türev" },
      { id: "meb26-12-matematik-integral", label: "İntegral" },
      { id: "meb26-12-matematik-analitik-geometri-ve-cember", label: "Analitik Geometri ve Çember" },
    ] },
    { id: "fizik", label: "Fizik", topics: [
      { id: "meb26-12-fizik-cembersel-hareket", label: "Çembersel Hareket" },
      { id: "meb26-12-fizik-basit-harmonik-hareket", label: "Basit Harmonik Hareket" },
      { id: "meb26-12-fizik-dalga-mekanigi", label: "Dalga Mekaniği" },
      { id: "meb26-12-fizik-atom-fizigine-giris-ve-radyoaktivite", label: "Atom Fiziğine Giriş ve Radyoaktivite" },
      { id: "meb26-12-fizik-modern-fizik", label: "Modern Fizik" },
      { id: "meb26-12-fizik-modern-fizigin-teknolojideki-uygulamalari", label: "Modern Fiziğin Teknolojideki Uygulamaları" },
    ] },
    { id: "kimya", label: "Kimya", topics: [
      { id: "meb26-12-kimya-kimya-ve-elektrik", label: "Kimya ve Elektrik" },
      { id: "meb26-12-kimya-karbon-kimyasina-giris", label: "Karbon Kimyasına Giriş" },
      { id: "meb26-12-kimya-organik-bilesikler", label: "Organik Bileşikler" },
      { id: "meb26-12-kimya-enerji-kaynaklari-ve-bilimsel-gelismeler", label: "Enerji Kaynakları ve Bilimsel Gelişmeler" },
    ] },
    { id: "biyoloji", label: "Biyoloji", topics: [
      { id: "meb26-12-biyoloji-genden-proteine", label: "Genden Proteine" },
      { id: "meb26-12-biyoloji-canlilarda-enerji-donusumleri", label: "Canlılarda Enerji Dönüşümleri" },
      { id: "meb26-12-biyoloji-bitki-biyolojisi", label: "Bitki Biyolojisi" },
      { id: "meb26-12-biyoloji-canlilar-ve-cevre", label: "Canlılar ve Çevre" },
    ] },
    { id: "t-c-inkilap-tarihi-ve-ataturkculuk", label: "T.C. İnkılap Tarihi ve Atatürkçülük", topics: [
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-20-yuzyil-baslarinda-osmanli-devleti-ve-dunya", label: "20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-mill-mucadele", label: "Millî Mücadele" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-ataturkculuk-ve-turk-inkilabi", label: "Atatürkçülük ve Türk İnkılabı" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-iki-savas-arasindaki-donemde-turkiye-ve-dunya", label: "İki Savaş Arasındaki Dönemde Türkiye ve Dünya" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-ii-dunya-savasi-surecinde-turkiye-ve-dunya", label: "II. Dünya Savaşı Sürecinde Türkiye ve Dünya" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-ii-dunya-savasi-sonrasinda-turkiye-ve-dunya", label: "II. Dünya Savaşı Sonrasında Türkiye ve Dünya" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-toplumsal-devrim-caginda-dunya-ve-turkiye", label: "Toplumsal Devrim Çağında Dünya ve Türkiye" },
      { id: "meb26-12-t-c-inkilap-tarihi-ve-ataturkculuk-21-yuzyilin-esiginde-turkiye-ve-dunya", label: "21. Yüzyılın Eşiğinde Türkiye ve Dünya" },
    ] },
    { id: "cografya", label: "Coğrafya", topics: [
      { id: "meb26-12-cografya-dogal-sistemler", label: "Doğal Sistemler" },
      { id: "meb26-12-cografya-beser-sistemler", label: "Beşerî Sistemler" },
      { id: "meb26-12-cografya-ekonomik-faaliyetler", label: "Ekonomik Faaliyetler" },
      { id: "meb26-12-cografya-bolgeler-ve-ulkeler", label: "Bölgeler ve Ülkeler" },
      { id: "meb26-12-cografya-cevre-ve-toplum", label: "Çevre ve Toplum" },
      { id: "meb26-12-cografya-turkiye-nin-bolgesel-ve-kuresel-baglantilari", label: "Türkiye’nin Bölgesel ve Küresel Bağlantıları" },
    ] },
    { id: "din-kulturu-ve-ahlak-bilgisi", label: "Din Kültürü ve Ahlak Bilgisi", topics: [
      { id: "meb26-12-din-kulturu-ve-ahlak-bilgisi-islam-ve-bilim", label: "İslam ve Bilim" },
      { id: "meb26-12-din-kulturu-ve-ahlak-bilgisi-anadolu-da-islam", label: "Anadolu’da İslam" },
      { id: "meb26-12-din-kulturu-ve-ahlak-bilgisi-islam-dusuncesinde-tasavvufi-yorumlar", label: "İslam Düşüncesinde Tasavvufi Yorumlar" },
      { id: "meb26-12-din-kulturu-ve-ahlak-bilgisi-guncel-din-meseleler", label: "Güncel Dinî Meseleler" },
      { id: "meb26-12-din-kulturu-ve-ahlak-bilgisi-hint-ve-cin-dinleri", label: "Hint ve Çin Dinleri" },
    ] },
  ] },
];

export function getGradeById(id: string) { return CURRICULUM.find((g) => g.id === id); }
export function getTopicById(topicId: string) { for (const grade of CURRICULUM) for (const subject of grade.subjects) { const topic = subject.topics.find((item) => item.id === topicId); if (topic) return { grade, subject, topic }; } }
export function allTopicIds() { const ids = new Set<string>(); for (const grade of CURRICULUM) for (const subject of grade.subjects) for (const topic of subject.topics) ids.add(topic.id); return ids; }
export function gradeTopicIds(gradeId: string) { const grade = getGradeById(gradeId); return new Set(grade?.subjects.flatMap((subject) => subject.topics.map((topic) => topic.id)) ?? []); }
export function guessGradeId(gradeLevel: string | null | undefined) { const raw = String(gradeLevel ?? "").toLocaleLowerCase("tr-TR"); const explicit = raw.match(/(?:^|\D)([5-9]|1[0-2])(?:\D|$)/)?.[1]; if (explicit) return explicit; if (raw.includes("lgs")) return "8"; if (raw.includes("yks") || raw.includes("mezun")) return "12"; return "8"; }