"use client";
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronUp, ExternalLink, MessageSquareQuote } from "lucide-react";
import { CURRICULUM, CURRICULUM_VERSION, getGradeById } from "@/lib/curriculum";
type ProgressRow={topicId:string;checkedAt:string|null;feedback:string|null;feedbackAt:string|null};
type ProgressMap=Record<string,{checked:boolean;feedback:string|null}>;
export default function MufredatClient({defaultGradeId}:{defaultGradeId:string}){
 const[gradeId,setGradeId]=useState(defaultGradeId);const[progress,setProgress]=useState<ProgressMap>({});const[loading,setLoading]=useState(true);const[openSubjects,setOpenSubjects]=useState<Set<string>>(new Set());
 useEffect(()=>{fetch("/api/student/topic-progress",{cache:"no-store"}).then(r=>r.json()).then((d:{progress?:ProgressRow[]})=>{const map:ProgressMap={};for(const row of d.progress??[])map[row.topicId]={checked:!!row.checkedAt,feedback:row.feedback};setProgress(map)}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 const grade=getGradeById(gradeId)??CURRICULUM[0];
 const toggleTopic=async(topicId:string)=>{const was=progress[topicId]?.checked??false;setProgress(p=>({...p,[topicId]:{checked:!was,feedback:p[topicId]?.feedback??null}}));try{const res=await fetch("/api/student/topic-progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId,checked:!was})});if(!res.ok)throw new Error()}catch{setProgress(p=>({...p,[topicId]:{checked:was,feedback:p[topicId]?.feedback??null}}))}};
 const toggleSubject=(id:string)=>setOpenSubjects(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next});
 const summary=useMemo(()=>{const subjects=grade.subjects.map(subject=>{const checked=subject.topics.filter(t=>progress[t.id]?.checked).length;return{...subject,checked,total:subject.topics.length,pct:subject.topics.length?Math.round(checked/subject.topics.length*100):0}});const checked=subjects.reduce((n,s)=>n+s.checked,0),total=subjects.reduce((n,s)=>n+s.total,0);return{subjects,checked,total,pct:total?Math.round(checked/total*100):0}},[grade,progress]);
 return <div><header className="mak-head"><span className="section-label">Konu Takibi · MEB {CURRICULUM_VERSION}</span><h1 className="section-title" style={{maxWidth:780}}>Çalıştığın Konuları <em>İşaretle</em></h1><p className="section-sub">Genel yüzde, seçtiğin sınıftaki tüm ders ve konuların toplamından hesaplanır. Birkaç işaretleme artık yapay biçimde %100 göstermez.</p></header>
 <div className="mufredat-grade-tabs" role="tablist" aria-label="Sınıf seç">{CURRICULUM.map(g=><button key={g.id} role="tab" aria-selected={g.id===gradeId} onClick={()=>setGradeId(g.id)} className={`mufredat-grade-tab${g.id===gradeId?" mufredat-grade-tab--active":""}`}>{g.label}</button>)}</div>
 <section className="mufredat-analytics"><div className="mufredat-overall"><div><span>GENEL MÜFREDAT İLERLEMESİ</span><strong>%{summary.pct}</strong><small>{summary.checked} / {summary.total} konu tamamlandı</small></div><div className="mufredat-ring" style={{"--progress":`${summary.pct*3.6}deg`} as React.CSSProperties}><b>{summary.pct}%</b></div></div><div className="mufredat-course-grid">{summary.subjects.map(s=><div className="mufredat-course-progress" key={s.id}><div><b>{s.label}</b><span>%{s.pct} · {s.checked}/{s.total}</span></div><i><em style={{width:`${s.pct}%`}}/></i></div>)}</div><a className="mufredat-source" href={grade.sourceUrl} target="_blank" rel="noopener noreferrer">MEB resmî program kaynağı <ExternalLink size={14}/></a></section>
 {loading?<p className="student-summary-empty" style={{marginTop:24}}>Yükleniyor…</p>:<div className="mufredat-subject-list">{summary.subjects.map(subject=>{const open=openSubjects.has(subject.id);return <div key={subject.id} className="mufredat-subject"><button className="mufredat-subject-head" onClick={()=>toggleSubject(subject.id)}><span className="mufredat-subject-title">{subject.label}</span><span className="mufredat-subject-percent">%{subject.pct}</span><span className="mufredat-subject-count">{subject.checked} / {subject.total}</span>{open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button><div className="mufredat-subject-bar"><i style={{width:`${subject.pct}%`}}/></div>{open&&<ul className="mufredat-topic-list">{subject.topics.map(topic=>{const state=progress[topic.id];return <li key={topic.id} className="mufredat-topic"><label className="mufredat-topic-label"><input type="checkbox" checked={!!state?.checked} onChange={()=>toggleTopic(topic.id)}/><span>{topic.label}</span></label>{state?.feedback&&<p className="mufredat-topic-feedback"><MessageSquareQuote size={14}/>{state.feedback}</p>}</li>})}</ul>}</div>})}</div>}
 </div>
}
