name: Prisma DB Push (Manuel)

on:
  workflow_dispatch:

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu indir
        uses: actions/checkout@v4

      - name: Node.js kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bağımlılıkları yükle
        run: npm ci

      - name: Prisma db push
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
